# Workflow name
name: Build
on:
# When it will be triggered
# And in which branch
  pull_request:
  push:
    branches:
      - master
# Where will they run
jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    steps:
    ## Checkout our repository ###
    - name: Checkout
      uses: actions/checkout@v2.3.3

    - name: Set up our JDK environment
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
    ## Build all our Build Types at once ##
    - name: Build all artifacts
      id: buildAllApks
      uses: eskatos/gradle-command-action@v1.3.3
      with:
        gradle-version: current
        wrapper-cache-enabled: true
        dependencies-cache-enabled: true
        configuration-cache-enabled: true
        arguments: assembleDebug
    - name: Upload to slack step
      uses: adrey/slack-file-upload-action@master
      with:
        token: xoxb-477257406901-2020818357207-7AzzzFWAsEx4aUrCfHFBej0l
        path: app/build/outputs/apk/debug/app-debug.apk
        channel: app
